[tool.poetry]
name = "orange-bank-api"
version = "0.1.0"
description = ""
authors = ["Alec McGavin <alec@mcgav.in>"]

[tool.poetry.dependencies]
python = "^3.7"
pycryptodomex = "^3.9.4"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
